what the fuck this this mean man
java.io.IOException: Failed to retrieve
	at com.unascribed.sup.agent.util.RequestHelper.lambda$get$1(RequestHelper.java:226)
	at com.unascribed.sup.agent.util.RequestHelper.withRetries(RequestHelper.java:251)
	at com.unascribed.sup.agent.util.RequestHelper.get(RequestHelper.java:160)
	at com.unascribed.sup.agent.util.RequestHelper.lambda$downloadToFile$2(RequestHelper.java:314)
	at com.unascribed.sup.agent.util.RequestHelper.withRetries(RequestHelper.java:251)
	at com.unascribed.sup.agent.util.RequestHelper.downloadToFile(RequestHelper.java:309)
	at com.unascribed.sup.agent.Agent.lambda$downloadAndCheckHash$8(Agent.java:823)
	at com.unascribed.sup.agent.util.RequestHelper.withRetries(RequestHelper.java:251)
	at com.unascribed.sup.agent.Agent.downloadAndCheckHash(Agent.java:822)
	at com.unascribed.sup.agent.Agent.lambda$applyUpdate$5(Agent.java:702)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method com.unascribed.sup.lib.okhttp3.Request$Builder.url, parameter
	at com.unascribed.sup.lib.okhttp3.Request$Builder.url(Request.kt)
	at com.unascribed.sup.agent.util.RequestHelper.lambda$get$1(RequestHelper.java:163)
	... 13 more